security:

    encoders:
        App\Component\Security\Core\User\UserInterface: bcrypt

    providers:
        system_user:
            id: App\Component\Security\Core\User\SystemUser

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_registration:
            pattern: ^/security/registration
            anonymous: true

        api_verification:
            pattern: ^/security/verification
            anonymous: true

        api_password_reset:
            pattern: ^/security/password-reset
            anonymous: true

        api_authentication:
            pattern: ^/security/authentication
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - App\Component\Security\Core\User\SystemUser
            #form_login:
            #    check_path: /security/authentication
                require_previous_session: false
            #    username_parameter: email
            #    password_parameter: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            logout: true

        api:
            pattern: ^/
            stateless: true
            lexik_jwt: ~

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/security/authentication, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/security/registration, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/security/verification, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/security/password-reset, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_FULLY }
